import Link from "next/link";
import {
  getBrief,
  getCandidates,
  getTrades,
  tradesById,
  type BriefPick,
  type Candidate,
} from "@/lib/data";
import { shortDate } from "@/lib/format";
import {
  ConvictionBadge,
  EvidenceChip,
  Plate,
  SectionHeader,
  SideTag,
  TickerLink,
} from "@/components/tags";

export default function BriefPage() {
  const brief = getBrief();
  const engine = getCandidates();
  const byId = tradesById();
  const nFilings = getTrades().trades.length;

  const generatedLine =
    brief.status === "ok"
      ? `Generated by ${brief.model ?? "claude"} from ${nFilings.toLocaleString()} filings on ${shortDate(brief.date ?? null)}.`
      : `Engine output only — the Claude brief was unavailable this run. Raw candidates below (as of ${shortDate(engine.as_of)}).`;

  return (
    <div className="space-y-10">
      <section>
        <SectionHeader
          plate="form cr-1 · daily brief"
          title="Today's Brief"
          right={
            <p className="mono max-w-[300px] text-right text-[11px] leading-relaxed text-muted-foreground">
              {generatedLine}
            </p>
          }
        />

        {brief.status === "ok" && brief.regime_note ? (
          <blockquote className="display mb-8 max-w-3xl border-l-2 border-brass/60 pl-4 text-[15px] italic leading-relaxed text-foreground/90">
            {brief.regime_note}
          </blockquote>
        ) : null}

        {brief.status === "ok" && brief.picks?.length ? (
          <div className="grid gap-4 lg:grid-cols-2">
            {brief.picks.map((p) => (
              <PickCard
                key={p.ticker}
                pick={p}
                candidate={engine.candidates.find((c) => c.ticker === p.ticker)}
                byId={byId}
              />
            ))}
          </div>
        ) : (
          <EngineFallback candidates={engine.candidates} />
        )}
      </section>

      <CautionSection brief={brief} caution={engine.caution} byId={byId} />

      {brief.status === "ok" && brief.skipped?.length ? (
        <section>
          <Plate>candidates set aside</Plate>
          <ul className="mt-2 grid gap-x-8 gap-y-1 text-xs text-muted-foreground sm:grid-cols-2 lg:grid-cols-3">
            {brief.skipped.map((s) => (
              <li key={s.ticker} className="flex gap-2">
                <TickerLink ticker={s.ticker} className="text-xs" />
                <span className="leading-relaxed">{s.reason}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}

function PickCard({
  pick,
  candidate,
  byId,
}: {
  pick: BriefPick;
  candidate?: Candidate;
  byId: ReturnType<typeof tradesById>;
}) {
  const fired = candidate
    ? Object.entries(candidate.signals)
        .filter(([, v]) => v.fired)
        .map(([k]) => k)
    : [];
  return (
    <article className="flex flex-col rounded-lg border border-border bg-card p-5">
      <header className="flex items-start justify-between gap-3">
        <div>
          <div className="flex items-baseline gap-3">
            <TickerLink ticker={pick.ticker} className="text-2xl tracking-tight" />
            <span
              className={`mono text-[11px] uppercase tracking-[0.14em] ${pick.direction === "long" ? "text-buy" : "text-sell"}`}
            >
              {pick.direction}
            </span>
          </div>
          {candidate?.name ? (
            <p className="mt-0.5 text-xs text-muted-foreground">{candidate.name}</p>
          ) : null}
        </div>
        <div className="flex flex-col items-end gap-1.5">
          <ConvictionBadge level={pick.conviction} />
          {candidate ? (
            <span className="mono text-[11px] text-brass" title="Engine composite score">
              CCS {candidate.score.toFixed(1)}
            </span>
          ) : null}
        </div>
      </header>

      <p className="mt-3 text-sm leading-relaxed text-foreground/90">{pick.thesis}</p>

      {fired.length ? (
        <p className="mono mt-3 text-[10px] uppercase tracking-[0.12em] text-muted-foreground">
          signals: <span className="text-brass">{fired.join(" + ")}</span>
        </p>
      ) : null}

      <div className="mt-3 space-y-2 border-t border-border pt-3 text-xs">
        <div>
          <span className="form-plate">key risks</span>
          <ul className="mt-1 list-inside space-y-0.5 text-muted-foreground">
            {pick.key_risks.map((r) => (
              <li key={r}>· {r}</li>
            ))}
          </ul>
        </div>
        <p>
          <span className="form-plate">invalidation</span>{" "}
          <span className="text-muted-foreground">{pick.invalidation}</span>
        </p>
        <p>
          <span className="form-plate">expression</span>{" "}
          <span className="text-muted-foreground">
            {pick.expression.simple}
            {pick.expression.defined_risk_note
              ? ` — ${pick.expression.defined_risk_note}`
              : ""}
          </span>
        </p>
      </div>

      <footer className="mt-auto flex flex-wrap gap-1.5 pt-4">
        {pick.evidence_ids.map((id) => (
          <EvidenceChip key={id} id={id} trade={byId.get(id)} />
        ))}
      </footer>
    </article>
  );
}

function EngineFallback({ candidates }: { candidates: Candidate[] }) {
  if (!candidates.length) {
    return (
      <p className="rounded-md border border-border bg-card p-6 text-sm text-muted-foreground">
        No scored candidates yet — the pipeline hasn&apos;t produced data. Once the
        daily run lands, the brief renders here.
      </p>
    );
  }
  return (
    <div className="overflow-x-auto rounded-lg border border-border bg-card">
      <table className="w-full text-left text-sm">
        <thead>
          <tr className="mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground">
            <th className="px-4 py-2.5 font-medium">Ticker</th>
            <th className="px-4 py-2.5 font-medium">Score</th>
            <th className="px-4 py-2.5 font-medium">Signals fired</th>
            <th className="px-4 py-2.5 font-medium">Buyers</th>
          </tr>
        </thead>
        <tbody className="ledger">
          {candidates.map((c) => (
            <tr key={c.ticker}>
              <td className="px-4 py-2">
                <TickerLink ticker={c.ticker} />
                <span className="ml-2 text-xs text-muted-foreground">{c.name}</span>
              </td>
              <td className="mono px-4 py-2 text-brass">{c.score.toFixed(1)}</td>
              <td className="mono px-4 py-2 text-xs text-muted-foreground">
                {Object.entries(c.signals)
                  .filter(([, v]) => v.fired)
                  .map(([k]) => k)
                  .join(" + ") || "—"}
              </td>
              <td className="mono px-4 py-2 tabular-nums">{c.stats.distinct_buyers}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function CautionSection({
  brief,
  caution,
  byId,
}: {
  brief: ReturnType<typeof getBrief>;
  caution: Candidate[];
  byId: ReturnType<typeof tradesById>;
}) {
  const items =
    brief.status === "ok" && brief.caution_list?.length
      ? brief.caution_list.map((c) => ({
          ticker: c.ticker,
          reason: c.reason,
          ids: c.evidence_ids ?? [],
          score: caution.find((x) => x.ticker === c.ticker)?.score,
        }))
      : caution.map((c) => ({
          ticker: c.ticker,
          reason: Object.entries(c.signals)
            .filter(([, v]) => v.fired)
            .map(([k]) => k.replace(/_/g, " "))
            .join(" + "),
          ids: c.evidence.map((e) => e.id),
          score: c.score,
        }));
  if (!items.length) return null;
  return (
    <section>
      <div className="rounded-lg border border-caution/30 bg-caution/5 p-5">
        <Plate>caution list · distribution &amp; sell clusters</Plate>
        <ul className="mt-3 space-y-3">
          {items.map((c) => (
            <li
              key={c.ticker}
              className="flex flex-wrap items-baseline gap-x-3 gap-y-1 text-sm"
            >
              <TickerLink ticker={c.ticker} />
              {typeof c.score === "number" ? (
                <span className="mono text-[11px] text-caution">{c.score.toFixed(1)}</span>
              ) : null}
              <SideTag side="sell" />
              <span className="text-muted-foreground">{c.reason}</span>
              <span className="flex flex-wrap gap-1">
                {c.ids.slice(0, 6).map((id) => (
                  <EvidenceChip key={id} id={id} trade={byId.get(id)} />
                ))}
              </span>
            </li>
          ))}
        </ul>
      </div>
      <p className="mt-3 text-xs text-muted-foreground">
        Full trade tape on the{" "}
        <Link href="/feed" className="text-brass hover:underline">
          feed
        </Link>
        ; cluster detail under{" "}
        <Link href="/clusters" className="text-brass hover:underline">
          clusters
        </Link>
        .
      </p>
    </section>
  );
}
